services:
    server:
        build: .
        platform: linux/amd64
        container_name: go-pdf
        networks:
            - go-pdf_network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 120s
        volumes:
            - ./config/:/app/config/
            - ./face/:/app/face/
            - ./templates/:/app/templates/
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        mem_limit: 2.5GB
        mem_reservation: 16M
        cpus: 2
        ports:
            - "10001:10001"
        environment:
            # CONFIG_PATH: "/app/config/prod.yaml" # uncomment for prod environment
            CONFIG_PATH: "/app/config/docker-debug.yaml" # uncomment for DEBUG in docker
    tests:
        build:
            context: .
            dockerfile: Dockerfile_tests
        mem_limit: 2.5GB
        mem_reservation: 16M
        cpus: 1
        container_name: go-pdf-test
        networks:
            - go-pdf_network
        volumes:
            - .:/app/

networks:
    go-pdf_network:
        driver: bridge
